AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  telegram-bot-webhook

  Sample SAM Template for telegram-bot-webhook

Globals:
  Function:
    Timeout: 3

Resources:
  TelegramBotFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: main.handler
      Runtime: python3.9
      Architectures:
        - x86_64
      Events:
        TelegramWebhook:
          Type: Api
          Properties:
            Path: /
            Method: post
      Environment:
        Variables:
          TELEGRAM_BOT_TOKEN: YOUR_TELEGRAM_BOT_TOKEN_HERE

Outputs:
  TelegramBotApi:
    Description: "API Gateway endpoint URL for Prod stage for Telegram Bot function"
    Value: !Sub "https://{ServerlessRestApi}.execute-api.{AWS::Region}.amazonaws.com/Prod/"